export const ENDPOINTS = {
    get_all_printers: `/printers/`,
    get_printer_by_id: (id) => `/printers/${id}/`,
    post_printer: `/printers/`,
    delete_printer: (id) => `/printers/${id}/`,
    update_printer: (id) => `/printers/${id}/`,
    get_all_computers: `/computers/`,
    get_computer_by_id: (id) => `/computers/${id}/`,
    post_new_computer: `/computers/`,
    delete_computer: (id) => `/computers/${id}/`,
    update_computer: (id) => `/computers/${id}/`,
    get_computers_by_pc_type: (pcType) => `/computers/?pc_type=${pcType}`,
    get_all_tablets: `/tablets/`,
    get_tablet_by_id: (id) => `/tablets/${id}/`,
    post_new_tablet: `/tablets/`,
    delete_tablet: (id) => `/tablets/${id}/`,
    get_all_monitors: `/monitors/`,
    get_monitor_by_id: (id) => `/monitors/${id}/`,
    post_new_monitor: `/monitors/`,
    delete_monitor: (id) => `/monitors/${id}/`,
    update_monitor: (id) => `/monitors/${id}/`,
    get_all_hardware_assets: `/hardware-assets/`,
    get_hardware_asset_by_id: (id) => `/hardware-assets/${id}/`,
    post_new_hardware_asset: `/hardware-assets/`,
    delete_hardware_asset: (id) => `/hardware-assets/${id}/`,
    update_hardware_asset: (id) => `/hardware-assets/${id}/`,
    get_all_branches: `org/branches/`,
    get_branch_by_id: (id) => `org/branches/${id}/`,
    post_new_branch: `org/branches/`,
    update_branch: (id) => `org/branches/update/${id}/`,
    delete_branch: (id) => `org/branches/${id}/`,
    get_all_sectors: `org/sectors/`,
    post_new_sector: `org/sectors/`,
    get_all_sectors_inside_branch: (branchId) => `org/branches/${branchId}/sectors/`,
    post_new_sector_inside_branch: (branchId) => `org/branches/${branchId}/sectors/`,
    delete_sector: (id) => `org/sectors/${id}/`,
    get_all_departments: `org/departments/`,
    get_all_departments_inside_sector: (sectorId) => `org/sectors/${sectorId}/departments/`,
    post_new_dept: `org/departments/`,
    delete_dept: (id) => `org/departments/${id}/`,
    get_all_employees: `custody/employees/`,
    post_new_employee: `custody/employees/add/`,
    delete_employee: (id) => `custody/employees/delete/${id}/`,
    get_employee_by_id: (id) => `custody/employees/${id}/`,
    update_employee: (id) => `custody/employees/update/${id}/`,
    assign_asset_to_employee: `custody/assign/`,
    replace_asset_from_stock_to_employee: `custody/replace/`,
    global_history_to_track_assets: `custody/history/global/`,
    history_to_track_assets_by_serial: (serialId) => `custody/history/asset/${serialId}/`,
    get_all_assigned_assets: `custody/assignments/active/`,
    get_assigned_employee_by_serial: (serialId) => `custody/lookup/${serialId}/`,
};
