export const ENDPOINTS = {
    get_all_printers: `/printers`,
    post_printer: `/printers`,
    delete_printer: (id) => `/printers/${id}`,
    get_all_computers: `/computers`,
    post_new_computer: `/computers`,
    delete_computer: (id) => `/computers/${id}`,
    get_computers_by_pc_type: (pcType) => `/computers/?pc_type=${pcType}`,
    get_all_tablets: `/tablets`,
    post_new_tablet: `/tablets`,
    delete_tablet: (id) => `/tablets/${id}`,
    get_all_hardware_assets: `/hardware-assets`,
    get_hardware_asset_by_id: (id) => `/hardware-assets/${id}`,
    post_new_hardware_asset: `/hardware-assets`,
    delete_hardware_asset: (id) => `/hardware-assets/${id}`,
    get_all_branches: `/branches`,
    post_new_branch: `/branches`,
    delete_branch: (id) => `/branches/${id}`,
    get_all_sectors: `/sectors`,
    post_new_sector: `/sectors`,
    get_all_sectors_inside_branch: (branchId) => `/branches/${branchId}/sectors`,
    post_new_sector_inside_branch: (branchId) => `/branches/${branchId}/sectors`,
    delete_sector: (id) => `/sectors/${id}`,
    get_all_departments: `/departments`,
    get_all_departments_inside_sector: (sectorId) => `/sectors/${sectorId}/departments`,
    post_new_dept: `/departments`,
    delete_dept: (id) => `/departments/${id}`,
    get_all_employees: `/employees`,


};